# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv') #part1 section 2

#Extracting the input features (independent variables) from the dataset.
#Here, we are using the iloc method to select all rows and all columns except the last one (the target variable).
#The .values attribute converts the extracted data into a NumPy array for further processing.
x =  dataset.iloc[:, :-1].values

# Extracting the target variable (dependent variable) from the dataset.
# Here, we are using the iloc method to select all rows and only the last column (the target variable column).
# The .values attribute converts the extracted data into a NumPy array for further processing.
y =  dataset.iloc[:, -1].values

In [ ]:
#or

# x = dataset.drop('Purchased', axis=1)
#y = dataset['Purchased']

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
# Importing the required library for data imputation
from sklearn.impute import SimpleImputer

# Creating an instance of the SimpleImputer class with specified parameters
# - missing_values: The value representing missing data, in this case, NaN (Not a Number)
# - strategy: The strategy used for imputation, here it is 'mean', which replaces missing values with the mean of the column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fitting the imputer on the data in the 2nd and 3rd columns of the 'x' array.
# The imputer computes the mean of these columns to be used for imputation.
imputer.fit(x[:, 1:3])

# Using the fitted imputer to transform the data in the 2nd and 3rd columns of the 'x' array.
# This replaces the missing values in these columns with their respective column means.
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
# Importing the required libraries for data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Creating a ColumnTransformer 'ct' to apply specific transformations to different columns of the input data 'x'.
# Here, we want to apply the OneHotEncoder to the first column ([0]) of the data 'x'.
# OneHotEncoder is used to convert categorical variables into numerical representation.
# The 'remainder' parameter is set to 'passthrough', which means any columns not specified in the transformers list will be retained as is.
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder='passthrough')

# Converting the 'x' DataFrame into a numpy array and simultaneously applying the transformations specified in 'ct'.
# The result of the transformation is stored back in 'x'.
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
# Importing the required library for data preprocessing
from sklearn.preprocessing import LabelEncoder

# Creating an instance of the LabelEncoder class
le = LabelEncoder()

# Using the LabelEncoder to transform the 'y' Series, which contains the target variable 'Purchased'.
# LabelEncoder is used to convert categorical labels (e.g., 'Purchased' categories) into numerical values.
# The 'fit_transform' method both fits the encoder to the data and transforms the data simultaneously.
# The transformed 'y' is now represented as numerical values.
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
# Importing the required library for splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

# Splitting the 'x' and 'y' data into training and testing sets.
# The 'test_size' parameter is set to 0.2, which means 20% of the data will be used for testing, and the remaining 80% for training.
# The 'random_state' parameter is set to 1, which ensures reproducibility of the split, i.e., the same split will be obtained every time the code is run with the same random_state value.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
# Importing the required library for feature scaling
from sklearn.preprocessing import StandardScaler

# Creating an instance of the StandardScaler class
sc = StandardScaler()

# Applying feature scaling on the numeric columns of 'x_train' and 'x_test' arrays
# The StandardScaler scales the data to have a mean of 0 and a standard deviation of 1, making the features more comparable and aiding the learning process for some machine learning algorithms.

# Scaling the data in the 'x_train' array, starting from the 4th column (index 3) until the end of the array.
# This means only the numeric columns (excluding the one-hot encoded columns) will be scaled.
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

# Scaling the data in the 'x_test' array, starting from the 4th column (index 3) until the end of the array.
# The 'transform' method is used here because we want to use the same scaling parameters (mean and standard deviation) computed on the 'x_train' data for the 'x_test' data.
x_test[:, 3:] = sc.transform(x_test[:, 3:])


In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
